### ISSUE TITLE
Upload of files is not possible

### ISSUE THREAD

**Issue by Sputnik2525** [YunoHost-Apps/audiobookshelf_ynh#114]
### Describe the bug
Link to forum entry https://forum.yunohost.org/t/audiobookshelf-upload-of-files-is-not-possible/28648/1

I installed the app from the official application "store". I have created a new user and try to upload a simple audiofile into the audiobookshel app.
Unforunately I get an error message called.

```
<html>

<head><title>413 Request Entity Too Large</title></head>

<body>

<center><h1>413 Request Entity Too Large</h1></center>

<hr><center>nginx</center>

</body>

</html>
```

### Context

- Hardware: *Dedicated AMD ryzon computer with Proxmox. yunohost runs as a VM*
- YunoHost version: 11.2.10.3
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: I mount nfs folders from a NAS
- Using, or trying to install package version/branch: 2.8.1

### Steps to reproduce

- *If the error occurs in your browser, explain what you did:*
   1. *Go to 'upload'*
   2. *Click on 'choose file'*
   3. *Choose file and click upload*
   4. *See error*

### Expected behavior

*The file uploads and is available in the UI.*

### What I tried to do
I checked the nginx configuration file and it shows at text `/etc/nginx/conf.d/audiobookshelf.<mydomain.tld>.d/audiobookshelf.conf `

It says that the upload limit is set to 10G

```
#sub_path_only rewrite ^/$ / permanent;
location / {

  proxy_pass http://127.0.0.1:8096;
  proxy_redirect    off;
  proxy_set_header  Host $host;
  proxy_set_header  X-Real-IP $remote_addr;
  proxy_set_header  X-Forwarded-Proto $scheme;
  proxy_set_header  X-Forwarded-Port $server_port;
  proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header  X-Forwarded-Host $server_name;
        
  proxy_pass_request_headers on;

  #WebSocket Support
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $http_connection;

  client_max_body_size 10G;

  # Include SSOWAT user panel.
  include conf.d/yunohost_panel.conf.inc;
}
```
### Logs

Where can I find logs for the application?

*When an operation fails, YunoHost provides a simple way to share the logs.*
- *In the webadmin, the error message contains a link to the relevant log page. On that page, you will be able to 'Share with Yunopaste'. If you missed it, the logs of previous operations are also available under Tools > Logs.*
- *In command line, the command to share the logs is displayed at the end of the operation and looks like `yunohost log display [log name] --share`. If you missed it, you can find the log ID of a previous operation using `yunohost log list`.*

*After sharing the log, please copypaste directly the link provided by YunoHost (to help readability, no need to copypaste the entire content of the log here, just the link is enough...)*

*If applicable and useful, add screenshots to help explain your problem.*

**Comment by tituspijean** [comment]
10G should be way enough indeed.

Can you share NGINX and Audiobookshelf's service logs right after truggering the error?

Can you also have a look to your browser's Network tab in developers console (F12 key), ans see which request fails?

**Comment by voiceoverguyuk** [comment]
I'm trying to upload a file 327MB, really small, but still says "413 Request Entity Too Large". Is there any update to get this working?

**Comment by tituspijean** [comment]
@voiceoverguyuk, I have been exchanging ideas with @Sputnik2525. Feel free to try to replicate their fix and my subsequent issue.

**Comment by brimwats** [comment]
@tituspijean it's a permissions error

```
2024-05-18 09:20:39.235

FATAL

[Server] Unhandled rejection: Error: EACCES: permission denied, mkdir '/home/yunohost.multimedia/REDACTED/eBook/Books/02. Audiobooks/Malka Older', promise: Promise { <rejected> [Error: EACCES: permission denied, mkdir '/home/yunohost.multimedia/REDACTED/eBook/Books/02. Audiobooks/Malka Older'] { errno: -13, code: 'EACCES', syscall: 'mkdir', path: '/home/yunohost.multimedia/REDACTED/eBook/Books/02. Audiobooks/Malka Older' } }
```

I don't know why its giving the filesize issue error in the popup but it does

![image](https://github.com/YunoHost-Apps/audiobookshelf_ynh/assets/73113656/b4f3abd8-30e5-4b0d-a308-6b9b1d7207ae)

**Comment by brimwats** [comment]
This issue persists in the latest update.

**Comment by brimwats** [comment]
I think giving audibookshelf pernission to write the folder would work, but I'm not sure how to do this; would it be:

```
usermod elasticsearch8 -a -G multimedia
setfacl -d -m u::rwX,g::rwX,o::r /home/yunohost.multimedia/USER/eBook/Books/02. Audiobooks
systemctl restart audiobookshelf
systemctl restart php7.4-fpm
systemctl restart php8.0-fpm
systemctl restart nginx
```

**Comment by brimwats** [comment]
After almost a year I've figured this out. It happens when you change the location of the Audiobookshelf Library. Mine is `Folder
/home/yunohost.multimedia/USERNAME/eBook/Books/02. Audiobooks`. If this looks like yours you have to `sudo nano /etc/group` and add audiobookshelf to the multimedia line: `multimedia:x:1003:calibreweb,jellyfin,immich,nextcloud,audiobookshelf`

**Comment by tituspijean** [comment]
@brimwats thank you for your investigation! Indeed the error got us in the wrong direction (though no permission =  upload limit at 0, kinda makes sense in a twisted way).
I have added the multimedia accesses in the aforementioned PR.
