### ISSUE TITLE
"Unhandled rejection: structuredClone is not defined" - Upgrade Node version 16 to 18

### ISSUE THREAD

**Issue by wojtek1171** [YunoHost-Apps/audiobookshelf_ynh#118]
Audiobookshelf currently crashes on `FATAL: [Server] Unhandled rejection: ReferenceError: structuredClone is not defined`  as 'structuredClone' function was introduced in Node 17.
 https://github.com/advplyr/audiobookshelf/issues/2854

Yunohost version of ABS uses node 16.2. Updating version in files in /opt/node_n/ynh_app_version or /etc/yunohost/apps/audiobookshelf doesn't make any changes.

**Comment by wojtek1171** [comment]
Any chances for that PR? I can't force ABS to use other version of node. Currently I had to change the part of the code with unhandled function to make it work.

**Comment by navanchauhan** [comment]
@wojtek1171 testing branch should work now. We will be merging it to master very soon
