### ISSUE TITLE
Test Apps with Server

### ISSUE THREAD

**Issue by navanchauhan** [YunoHost-Apps/audiobookshelf_ynh#2]
Need to test Android and iOS apps with the server and make sure everything is working

**Comment by navanchauhan** [comment]
Thovi98 successfully tested this with the android app, but the server is crashing when I use an iOS app. I did add restartAlways to the systemd file so it should recover from it.

Need to investigate the issue for the iOS app and potentially test with the android client myself as well.

**Comment by Thovi98** [comment]
Maybe check this to see if the error still occurs ? https://github.com/advplyr/audiobookshelf/issues/345#issuecomment-1028020903

**Comment by navanchauhan** [comment]
@Thovi98 Tested it on android and iOS for a couple of weeks. No issues like the linked comment 

Closing this issue for now because I am happy
