### ISSUE TITLE
Unable to upload any of my audiobooks

### ISSUE THREAD

**Issue by VOGUK** [YunoHost-Apps/audiobookshelf_ynh#90]
**Hardware:** Thinkpad Laptop – Intel i5 – 4GB RAM
**YunoHost version:** Latest ISO – fresh install
**I have access to my server :** SSH & Web Admin
**Are you in a special context or did you perform some particular tweaking on your YunoHost instance? :** No
If yes, please explain:

**Description of my issue:**
Hi all, I can't upload any of my audiobooks. I get the following error:
<html>
<head><title>413 Request Entity Too Large</title><script type="text/javascript" src="/ynh_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynh_overlay.css"><script type="text/javascript" src="/ynhtheme/custom_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css"></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>

Any idea how I can fix it?

**Comment by navanchauhan** [comment]
* How big are the files?
* Also, how are you uploading the files?

**Comment by VOGUK** [comment]
Hi, the first file I'm trying to upload it about 320MB. All of the metadata propigates correctly. I'm uploading from the Audiobookshelf webpage clicking on the upload arrow in the top right-hand-side of the GUI.

**Comment by navanchauhan** [comment]
Ah okay, that makes sense, I never use the web upload.

This is because of Nginx's configuration we are using right now:

>   client_max_body_size 100M;

CC @Thovi98 

Should we up this to 2GB?

**Comment by VOGUK** [comment]
Yes, that would be great as the majority of files are above 100MB.

**Comment by navanchauhan** [comment]
@VOGUK please test the new update
